language: go
sudo: false

go:
  - 1.10.x
  - tip

before_install:
  - go get -u github.com/golang/dep/...
  - dep ensure

script:
  - ./testCoverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)